name: blinder
description: App hen ho

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.3
  get_storage: ^2.0.3
  intl: ^0.17.0

  # Let your UI display a reasonable layout on different screen sizes!
  flutter_screenutil: ^5.5.3+1
  flutter_svg: ^0.22.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: 2.1.0

  shared_preferences: ^2.0.5
  # Share images
  url_launcher: ^6.0.9
  dio: ^4.0.0
  sqflite: ^2.0.0+3

  image_picker: ^0.7.4

  #Slidable
  flutter_slidable: ^1.2.0

  cached_network_image: ^3.1.0
  flutter_launcher_icons: ^0.9.2

  google_sign_in: ^5.2.4
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.12

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
